<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NLog" Version="6.2.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>    
    <ProjectReference Include="..\..\..\CreateInvoiceSystem.Shared.Persistence\CreateInvoiceSystem.Shared.Persistence.csproj" />    
    <ProjectReference Include="..\..\CreateInvoiceSystem.Abstractions\CreateInvoiceSystem.Abstractions.csproj" />    
    
  </ItemGroup>

</Project>
