trigger:
  branches:
    include:
      - master

pr: none  

resources:
  repositories:
    - repository: self
      type: git

pool:
  name: 'CreateInvoiceSystemPool'

variables:
  buildConfiguration: 'Release'

steps:

- checkout: self

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- script: dotnet restore $(Build.SourcesDirectory)\CreateInvoiceSystem.sln
  displayName: '🔄 Restore NuGet packages'

- script: dotnet build $(Build.SourcesDirectory)\CreateInvoiceSystem.sln --configuration $(buildConfiguration)
  displayName: '🛠️ Build solution'

- script: dotnet test $(Build.SourcesDirectory)\CreateInvoiceSystem.BuildTests\CreateInvoiceSystem.BuildTests.csproj --configuration $(buildConfiguration)
  displayName: '🧪 Run build verification test'
