<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />  
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Web.AspNetCore" />
  </ItemGroup>

  <ItemGroup>    
    <ProjectReference Include="..\..\CreateInvoiceSystem.Abstractions\CreateInvoiceSystem.Abstractions.csproj" />
  </ItemGroup>  

</Project>
