<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>    
    <ImplicitUsings>enable</ImplicitUsings>    
    <UserSecretsId>bf1126bf-c7d8-4f7f-8e88-42931a9af132</UserSecretsId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Web.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="RestSharp" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CreateInvoiceSystem.Abstractions\CreateInvoiceSystem.Abstractions.csproj" />
    <ProjectReference Include="..\CreateInvoiceSystem.Csv\CreateInvoiceSystem.Csv.csproj" />
    <ProjectReference Include="..\CreateInvoiceSystem.Identity\CreateInvoiceSystem.Identity.csproj" />
    <ProjectReference Include="..\CreateInvoiceSystem.Mail\CreateInvoiceSystem.Mail.csproj" />
    <ProjectReference Include="..\CreateInvoiceSystem.Pdf\CreateInvoiceSystem.Pdf.csproj" />
    <ProjectReference Include="..\CreateInvoiceSystem.Persistence\CreateInvoiceSystem.Persistence.csproj" />
    <ProjectReference Include="..\Modules\CreateInvoiceSystem.Modules.Clients\CreateInvoiceSystem.Modules.Clients.csproj" />
    <ProjectReference Include="..\Modules\CreateInvoiceSystem.Modules.Invoices\CreateInvoiceSystem.Modules.Invoices.csproj" />
    <ProjectReference Include="..\Modules\CreateInvoiceSystem.Modules.Nbp\CreateInvoiceSystem.Modules.Nbp.csproj" />
    <ProjectReference Include="..\Modules\CreateInvoiceSystem.Modules.Products\CreateInvoiceSystem.Modules.Products.csproj" />
    <ProjectReference Include="..\Modules\CreateInvoiceSystem.Modules.Users\CreateInvoiceSystem.Modules.Users.csproj" />
  </ItemGroup>
</Project>
